### ISSUE TITLE
Call to undefined method: Rinvex\Tenants\Models\Tenant::create()

### ISSUE THREAD

**Issue by Peter2962** [rinvex/tenants#15]
I am trying to create a tenant with this code:

app('rinvex.tenants.tenant')->create([
			'name' => 'ACME Inc.',
			'slug' => 'acme',
			'owner_id' => '1',
			'email' => 'owner@acme.inc',
			'language_code' => 'en',
			'country_code' => 'us',
		]);
But i keep getting **Call to undefined method: Rinvex\Tenants\Models\Tenant::create()**. Thank you.

**Comment by Omranic** [comment]
Tested & seems to be working smoothly, that's not expected behavior as the `create` method is a default eloquent method, and the `Tenant` model extends eloquent natively, so that's really weird! I just tested the code above & it worked for me anyway..

**Comment by Peter2962** [comment]
Oh okay. I am using it with L5.5 by the way. Thanks.

**Comment by Peter2962** [comment]
I am not sure what is wrong because it is a new project that i just setup.

**Comment by Omranic** [comment]
Yes, tested on Laravel v5.5. Try to create a new instance explicitely like that: `$tenant = new \Rinvex\Tenants\Models\Tenant();` and let me know what happens..

P.S. All of our packages now require Laravel v5.5 and PHP v7.0 at least 😉

**Comment by Peter2962** [comment]
I created a new instance and did not get any errors. And yes i am using PHP v7.0.9. Thank you.

**Comment by Omranic** [comment]
Then that's even stranger! Try to publish config file via `php artisan rinvex:publish:tenants` and try again the first code sample..

**Comment by Peter2962** [comment]
I dumped it and got the object.

Tenant {#291 ▼
  #fillable: array:15 [▶]
  #casts: array:14 [▶]
  #observables: array:2 [▶]
  +translatable: array:2 [▶]
  #rules: array:15 [▶]
  #throwValidationExceptions: true
  #connection: null
  #table: "tenants"
  #primaryKey: "id"
  #keyType: "int"
  +incrementing: true
  #with: []
  #withCount: []
  #perPage: 15
  +exists: false
  +wasRecentlyCreated: false
  #attributes: []
  #original: []
  #changes: []
  #dates: []
  #dateFormat: null
  #appends: []
  #dispatchesEvents: []
  #relations: []
  #touches: []
  +timestamps: true
  #hidden: []
  #visible: []
  #guarded: array:1 [▶]
  #slugOptions: null
  #validationErrors: null
  #validating: true
  #validator: null
  #validationAttributeNames: null
  #cacheDriver: null
  #cacheLifetime: -1
}

**Comment by Peter2962** [comment]
Can you please give me the steps to follow when setting it up? Maybe i'm not following the correct steps/instructions? Thank you.

**Comment by Omranic** [comment]
As per the docs there's only two required installation steps:
```shell
composer require rinvex/tenants
php artisan rinvex:migrate:tenants
```
And optionally:
```shell
php artisan rinvex:publish:tenants
```

https://github.com/rinvex/tenants/tree/develop#installation

**Comment by Peter2962** [comment]
I'm not sure, does a user have to be logged in?

**Comment by Omranic** [comment]
A user must be logged in for tenants to take effect, but that has nothing to do with the creation process itself. You still have the same method not found errors after publishing configure?

**Comment by Peter2962** [comment]
Okay cool. Yes i still have the same errors.

**Comment by Peter2962** [comment]
Is there anywhere i can add a dump to see where data should be writing?

**Comment by Peter2962** [comment]
Hi @Omranic , 

I hope you are well? Regarding this same issue, if i remove **ValidatingTrait** from TenantsModel and also comment out some lines of code from the TenantsModel it works. Please see code that was commented out below:

        $this->setRules([
            'slug' => 'required|alpha_dash|max:150|unique:'.config('rinvex.tenants.tables.tenants').',slug',
            'name' => 'required|string|max:150',
            'description' => 'nullable|string|max:10000',
            'owner_id' => 'required|integer|exists:'.(new $userModel())->getTable().',id',
            'email' => 'required|email|min:3|max:150|unique:'.config('rinvex.tenants.tables.tenants').',email',
            'phone' => 'nullable|numeric|min:4',
            'country_code' => 'required|alpha|size:2|country',
            'language_code' => 'required|alpha|size:2|language',
            'state' => 'nullable|string',
            'city' => 'nullable|string',
            'address' => 'nullable|string',
            'postal_code' => 'nullable|string',
            'launch_date' => 'nullable|date_format:Y-m-d',
            'group' => 'nullable|string|max:150',
            'is_active' => 'sometimes|boolean',
        ]);

        static::validating(function (self $tenant) {
            if ($tenant->exists && $tenant->getSlugOptions()->generateSlugsOnUpdate) {
                $tenant->generateSlugOnUpdate();
            } elseif (! $tenant->exists && $tenant->getSlugOptions()->generateSlugsOnCreate) {
                $tenant->generateSlugOnCreate();
            }
        });

Thank you.

**Comment by Omranic** [comment]
Well, I hope we can help you. But this issue couldn't be reproduced on any project up until now, which makes us believe it doesn't exist or maybe related to your own setup. If you can provide detailed steps on how to reproduce this issue I'll be happy to followup & fix if confirmed 🙂

**Comment by Peter2962** [comment]
Hi @Omranic ,

Great thank you. There is no other detail to provide as the details provided above is the only details available. Just one thing, after commenting out the codes provided above, i am now able to use **create** method to save the a tenant.
